### ISSUE TITLE
When will you release the code, trained checkpoints and installation guide?

### ISSUE THREAD

**Issue by nitinmukesh** [lil-lab/ICCA#2]

**Comment by yilun-hua** [comment]
Thank you for your interest in our work! 

Our code and installation instruction were already released through this repo when our paper went public on ArXiv. You can find our code in the `src` folder. I also updated the README with a more streamlined way of installation. Hope this helps!

All the open-sourced checkpoints we evaluated for our paper will be automatically downloaded when you run our code. For the closed-source models, you will need API access. Please refer to the official website of OpenAI, Google Gemini, and Anthropic for steps of getting API access.
